name: Run Newsflash Tweet Script

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify your Python version here.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz openai python-dotenv supabase

    - name: Load Environment Variables
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV
        echo "OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}" >> $GITHUB_ENV
        echo "HEADER_TOKEN=${{ secrets.HEADER_TOKEN }}" >> $GITHUB_ENV
        echo "X_API_KEY=${{ secrets.X_API_KEY }}" >> $GITHUB_ENV
        echo "X_KR_API_KEY=${{ secrets.X_KR_API_KEY }}" >> $GITHUB_ENV

    - name: Execute Python script
      run: python newsflash-tweet.py  # Update the path to where your script is located in the repository.
